apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-frontend
spec:
  replicas: {{ .Values.frontendPortal.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-frontend
    spec:
      containers:
      - name: {{ .Values.name }}-frontend
        image: {{ .Values.frontendPortal.image }}
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.frontendPortal.portContainer }}
