name: cx-portal

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo user ${{ github.actor }}

      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn

      - name: Linter Checks
        run: yarn lint

      - name: Build Library and Portal
        run: yarn build
        
      - name: Unit Tests
        working-directory: ./cx-portal
        run: yarn test

      - name: Publish Shared Components to npm
        working-directory: ./cx-portal-shared-components
        run: echo yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "./conf/Dockerfile.prebuilt"
          tags: ${{ github.actor }}/portal-frontend:latest

#      - name: Build Docker Image
#        run: yarn build:docker

#      - name: Publish Docker Image
#        run: yarn publish:docker
