name: cx-portal

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn

      - name: Build Shared UI Library
        working-directory: ./cx-portal-shared-components
        run: |
          yarn build:lib
        
      - name: Linter Checks
        run: |
          yarn lint

      - name: Unit Tests
        working-directory: ./cx-portal
        run: |
          yarn test

      - name: Build Portal Frontend
        working-directory: ./cx-portal
        run: |
          yarn build

      - name: Docker Build
        run: |
          yarn build:docker
