name: cx-portal

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Linter Checks
        run: yarn lint

      - name: Build Library and Portal
        run: yarn build
        
      - name: Unit Tests
        working-directory: ./cx-portal
        run: yarn test

      - name: 'Login to Docker Registry'
        uses: azure/docker-login@v1
        with:
          login-server: catenaxacr.azurecr.io
          username: catenaxacr
          password: ${{secrets.AZURE_REGISTRY_PASSWORD}}

      - name: Build Docker Image
        run: yarn build:docker

      - name: Publish Docker Image
        run: yarn publish:docker
