name: cx-portal

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Linter Checks
        run: yarn lint

      - name: Build Library and Portal
        run: yarn build

      - name: Unit Tests
        run: yarn test:ci

      - name: Publish Shared Components to npm
        working-directory: ./cx-portal-shared-components
        run: echo yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./.conf/Dockerfile.prebuilt
          tags: ghcr.io/${{ github.actor }}/cx-portal-frontend:latest
